soc_brand:
  ingenic: &soc_brand_ingenic
    brand: ingenic
    docs_url: https://github.com/themactep/wiki/blob/master/hardware/components/soc/ingenic.md

soc_family:
  ingenic_tpl: &soc_family_ingenic_tpl
    family: --
    cpu_arch: --
    max_resolution: --
    max_encoding: --
  ingenic_T10: &soc_family_ingenic_T10
    family: T10
    cpu_arch: XBurst1
    max_resolution: 1280x1024
    max_encoding: 960p@40fps
  ingenic_T20: &soc_family_ingenic_T20
    family: T20
    cpu_arch: XBurst1
    max_resolution: 2048x1536
    max_encoding: no hw?
  ingenic_T21: &soc_family_ingenic_T21
    family: T21
    cpu_arch: XBurst1
    max_resolution: 2048x2048
    max_encoding: 1920x1080@40fps
  ingenic_T21: &soc_family_ingenic_T23
    family: T23
    cpu_arch: XBurst1
    max_resolution: 2308x2048
    max_encoding: 3MP@40fps
  ingenic_T30: &soc_family_ingenic_T30
    family: T30
    cpu_arch: XBurst1
    max_resolution: 2688x2048
    max_encoding: 3840x2160@30fps
  ingenic_T31: &soc_family_ingenic_T31
    family: T31
    cpu_arch: XBurst1
    max_resolution: 2592x2048
    max_encoding: 2592x2048@25fps

soc:
  tpl: &soc_tpl
    <<: *soc_brand_ingenic
    <<: *soc_family_ingenic_tpl
    name: --
    ram_mb: "--:"
    cpu_clock_mhz: "--:"
  T10L: &soc_T10L
    <<: *soc_brand_ingenic
    <<: *soc_family_ingenic_T10
    name: T10L
    ram_mb: 64
    cpu_clock_mhz: 860
  T20L: &soc_T20L
    <<: *soc_brand_ingenic
    <<: *soc_family_ingenic_T20
    name: T20L
    ram_mb: 64
    cpu_clock_mhz: 800
  T20X: &soc_T20X
    <<: *soc_brand_ingenic
    <<: *soc_family_ingenic_T20
    name: T20X
    ram_mb: 128
    cpu_clock_mhz: 800
  T21N: &soc_T21N
    <<: *soc_brand_ingenic
    <<: *soc_family_ingenic_T21
    name: T21N
    ram_mb: 64
    cpu_clock_mhz: 800
  T21Z: &soc_T21Z
    <<: *soc_brand_ingenic
    <<: *soc_family_ingenic_T21
    name: T21Z
    ram_mb: 64
    cpu_clock_mhz: 800
  T23N: &soc_T23N
    <<: *soc_brand_ingenic
    <<: *soc_family_ingenic_T23
    name: T23N
    ram_mb: 64
    cpu_clock_mhz: 1400
  T30L: &soc_T30L
    <<: *soc_brand_ingenic
    <<: *soc_family_ingenic_T30
    name: T30L
    ram_mb: 64
    cpu_clock_mhz: 1000
  T30X: &soc_T30X
    <<: *soc_brand_ingenic
    <<: *soc_family_ingenic_T30
    name: T30X
    ram_mb: 128
    cpu_clock_mhz: 1000
  T31AL: &soc_T31AL
    <<: *soc_brand_ingenic
    <<: *soc_family_ingenic_T31
    name: T31AL
    ram_mb: 128
    cpu_clock_mhz: 1500
  T31L: &soc_T31L
    <<: *soc_brand_ingenic
    <<: *soc_family_ingenic_T31
    name: T31L
    ram_mb: 64
    cpu_clock_mhz: 1000
  T31LC: &soc_T31LC
    <<: *soc_brand_ingenic
    <<: *soc_family_ingenic_T31
    name: T31LC
    ram_mb: ??
    cpu_clock_mhz: ??
  T31N: &soc_T31N
    <<: *soc_brand_ingenic
    <<: *soc_family_ingenic_T31
    name: T31N
    ram_mb: 64
    cpu_clock_mhz: 1400
  T31X: &soc_T31X
    <<: *soc_brand_ingenic
    <<: *soc_family_ingenic_T31
    name: T31X
    ram_mb: 128
    cpu_clock_mhz: 1400
  T31ZX: &soc_T31ZX
    <<: *soc_brand_ingenic
    <<: *soc_family_ingenic_T31
    name: T31ZX
    ram_mb: 128
    cpu_clock_mhz: 1400



sensor:
  tpl: &sensor_tpl
    name: --
    resolution: --
    docs_url: "--"
  GC1084: &sensor_GC1084
    name: GC1084
    resolution: ??
    docs_url: "??"
  GC2053: &sensor_GC2053
    name: GC2053
    resolution: 1920x1080@30fps
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/galaxycore.md"
  GC2083: &sensor_GC2083
    name: GC2083
    resolution: 1920x1080@30fps
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/galaxycore.md"
  GC4653: &sensor_GC4653
    name: GC4653
    resolution: 2560x1440@30fps
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/galaxycore.md"
  IMX327: &sensor_IMX327
    name: IMX327
    resolution: 2136x2781@5~25fps
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/sony.md"
  JXF22: &sensor_JXF22
    name: JXF22
    resolution: 1920x1080@60fps
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/soi.md"
  JXF23: &sensor_JXF23
    name: JXF23
    resolution: 1920x1080@30fps
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/soi.md"
  JXF37: &sensor_JXF37
    name: JXF37
    resolution: 2400x1440@5~30fps
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/soi.md"
  JXH42: &sensor_JXH42
    name: JXH42
    resolution: ??@60fps
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/soi.md"
  JXH62: &sensor_JXH62
    name: JXH62
    resolution: ??@60fps
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/soi.md"
  JXK04: &sensor_JXK04
    name: JXK04
    resolution: 2560x1440@5~30fps
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/soi.md"
  JXQ03: &sensor_JXQ03
    name: JXQ03
    resolution: 3600x1600@5~30fps ???
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/soi.md"
  JXQ03P: &sensor_JXQ03P
    name: JXQ03p
    resolution: 2304x1296@5~30fps ???
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/soi.md"
  OS02B10: &sensor_OS02B10
    name: OS02B10
    resolution: 1600x1200@30fps
    docs_url: "https://www.ovt.com/wp-content/uploads/2022/01/OV02B-PB-v1.1-WEB.pdf"
  OS02G10: &sensor_OS02G10
    name: OS02G10
    resolution: 1920x1080@30fps
    docs_url: "https://www.ovt.com/wp-content/uploads/2022/01/OS02G10-PB-v1.2-WEB.pdf"
  OV2735B: &sensor_OV2735B
    name: OV2735b
    resolution: 2106x1595@5~30fps
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/omnivision.md"
  SC1235: &sensor_SC1235
    name: SC1235
    resolution: 1800x1200@30fps
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/smartsens.md"
  SC1A4T: &sensor_SC1A4T
    name: SC1A4T
    resolution: ???
    docs_url: ""
  SC2235: &sensor_SC2235
    name: SC2235
    resolution: 1920x1080@50fps
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/smartsens.md"
  SC223A: &sensor_SC223A
    name: SC223A
    resolution: 1920x1080@30fps
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/smartsens.md"
  SC2300: &sensor_SC2300
    name: SC2300
    resolution: 1920x1080@30fps
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/smartsens.md"
  SC2332: &sensor_SC2332
    name: SC2332
    resolution: 1920x1080@30fps
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/smartsens.md"
  SC2336: &sensor_SC2336
    name: SC2336
    resolution: 1920x1080@30fps
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/smartsens.md"
  SC3335: &sensor_SC3335
    name: SC3335
    resolution: 2500x1620@30fps ???
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/smartsens.md"
  SC3336: &sensor_SC3336
    name: SC3336
    resolution: 2304x1296@30fps
    docs_url: "https://smartsens.oss-cn-beijing.aliyuncs.com/web/img/1631255683627289713.pdf"
  SC401AI: &sensor_SC401AI
    name: SC401AI
    resolution: 2560x1440@30fps
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/smartsens.md"
  SC4236: &sensor_SC4236
    name: SC4236
    resolution: 2304x1536@30fps
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/smartsens.md"
  SC4336: &sensor_SC4336
    name: SC4336
    resolution: 2560x1440@30fps
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/sensor/smartsens.md"
  SC4336P: &sensor_SC4336P
    name: SC4336p
    resolution: 2880x1620@30fps ???
    docs_url: "https://smartsens.oss-cn-beijing.aliyuncs.com/web/img/1677747703063551255.pdf"



wifi:
  tpl: &wifi_tpl
    name: --
    interface: --
    w2g: --
    w2g_radio: --
    w2g_HT40: --
    w5g: --
    docs_url: "--"
  ATBM6012B: &wifi_ATBM6012B
    name: ATBM6012B
    interface: USB
    w2g: b/g/n
    w2g_radio: 1T1R
    w2g_HT40: false
    w5g: false
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/wireless/altobeam.md"
  ATBM6012BX: &wifi_ATBM6012BX
    name: ATBM6012BX
    interface: USB
    w2g: b/g/n
    w2g_radio: 1T1R
    w2g_HT40: false
    w5g: false
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/wireless/altobeam.md"
  ATBM6031: &wifi_ATBM6031
    name: ATBM6031
    interface: SDIO
    w2g: b/g/n
    w2g_radio: 1T1R
    w2g_HT40: true
    w5g: false
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/wireless/altobeam.md"
  ATBM6032: &wifi_ATBM6032
    name: ATBM6032
    interface: USB
    w2g: b/g/n
    w2g_radio: 1T1R
    w2g_HT40: true
    w5g: false
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/wireless/altobeam.md"
  ATBM6062: &wifi_ATBM6062
    name: ATBM6062
    interface: USB
    w2g: b/g/n/ax
    w2g_radio: 1T1R
    w2g_HT40: true
    w5g: false
    docs_url: "https://github.com/themactep/wiki/blob/master/hardware/components/wireless/altobeam.md"
  ETH: &wifi_ETH
    name: --
    interface: --
    w2g: --
    w2g_radio: --
    w2g_HT40: --
    w5g: --
    docs_url: "--"
  HI3881: &wifi_HI3881
    name: HI3881
    interface: SDIO
    w2g: b/g/n
    w2g_radio: 1T1R
    w2g_HT40: false
    w5g: false
    docs_url: "??"
  MT7601: &wifi_MT7601
    name: MT7601
    interface: ??
    w2g: ??
    w2g_radio: ??
    w2g_HT40: ??
    w5g: ??
    docs_url: "??"
  MT7601U: &wifi_MT7601U
    name: MT7601U
    interface: ??
    w2g: ??
    w2g_radio: ??
    w2g_HT40: ??
    w5g: ??
    docs_url: "??"
  MT7601STA: &wifi_MT7601STA
    name: MT7601STA
    interface: USB?
    w2g: b/g/n
    w2g_radio: 1T1R
    w2g_HT40: true
    w5g: false
    docs_url: "https://github.com/themactep/thingino-firmware/blob/master/package/wifi-mt7601sta/wifi-mt7601sta.mk"
  RTL8188FTV: &wifi_RTL8188FTV
    name: RTL8188FTV
    interface: USB
    w2g: b/g/n
    w2g_radio: 1T1R
    w2g_HT40: true
    w5g: false
    docs_url: "https://xonstorage.blob.core.windows.net/pdf/realtek_rtl8188ftvvccg_apr22_xonlink.pdf"
  RTL8189ETV: &wifi_RTL8189ETV
    name: RTL8189ETV
    interface: SDIO
    w2g: b/g/n
    w2g_radio: 1T1R
    w2g_HT40: true
    w5g: false
    docs_url: "https://www.semiee.com/file/Realtek/Realtek-RTL8189ETV.pdf"
  RTL8189FTV: &wifi_RTL8189FTV
    name: RTL8189FTV
    interface: SDIO
    w2g: b/g/n
    w2g_radio: 1T1R
    w2g_HT40: true
    w5g: false
    docs_url: "https://wmsc.lcsc.com/wmsc/upload/file/pdf/v2/lcsc/2407020948_Realtek-Semicon-RTL8189FTV-VC-CG_C2687145.pdf"
  RTL8192FC: &wifi_RTL8192FC
    name: RTL8192FC
    interface: PCIe
    w2g: b/g/n
    w2g_radio: 2T2R
    w2g_HT40: true
    w5g: false
    docs_url: "https://fccid.io/pdf.php?id=1291410"
  SSV6155: &wifi_SSV6155
    name: SSV6155
    interface: ??
    w2g: ??
    w2g_radio: ??
    w2g_HT40: ??
    w5g: ??
    docs_url: "??"
  SSV6158: &wifi_SSV6158
    name: SSV6158
    interface: SDIO
    w2g: b/g/n
    w2g_radio: 1T1R
    w2g_HT40: true
    w5g: false
    docs_url: "http://www.icomm-semi.com/Uploads/Temp/files/2022-08-18/SV6158%20Datasheet%20V1.2.pdf"
  SSV6355: &wifi_SSV6355
    name: SSV6355
    interface: ??
    w2g: ??
    w2g_radio: ??
    w2g_HT40: ??
    w5g: ??
    docs_url: "??"
  SYN43436: &wifi_SYN43436
    name: SYN43436
    interface: ??
    w2g: ??
    w2g_radio: ??
    w2g_HT40: ??
    w5g: ??
    docs_url: "??"
  SYN43438: &wifi_SYN43438
    name: SYN43438
    interface: ??
    w2g: ??
    w2g_radio: ??
    w2g_HT40: ??
    w5g: ??
    docs_url: "??"


